{"name": "Division", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 22, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "steps": [{"name": "Given I have a calculator", "status": "passed", "start": 1689109998678, "stop": 1689109998678}, {"name": "When I enter \"10\" as the first number", "status": "passed", "start": 1689109998678, "stop": 1689109998679}, {"name": "And I enter \"/\" as the operation", "status": "passed", "start": 1689109998679, "stop": 1689109998680}, {"name": "And I enter \"2\" as the second number", "status": "passed", "start": 1689109998680, "stop": 1689109998682}, {"name": "Then the answer should be \"5\"", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dell\\Desktop\\Bootcamp\\CICD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\calcSteps.py\", line 22, in step_then_check_answer\n    assert actual_answer == expected_answer\n"}, "start": 1689109998682, "stop": 1689109998683}], "start": 1689109998676, "stop": 1689109998684, "uuid": "60936846-89a7-48f5-a817-4fbfd99028e2", "historyId": "ba97aaca913a6129cf0224cf97d9d863", "fullName": "Calculator: Division", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Calculator"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}